version : '3.9'

services: 
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
  
  app1:
    image: node:latest
    container_name: node_app1
    build: 
      context: ./app
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    #command: ["node", "server.js"] -> 오버라이드 해버림
    expose:
      - "3000"

  app2:
    image: node:latest
    container_name: node_app2
    build: 
      context: ./app
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    #command: ["node", "server.js"]
    expose:
      - "3000"
    